BEGIN;
-- Kontext: image_url fuer bestehende Vokabeln (Lektionen 212/213), 2026-09-26
-- Erwartete Zeilen: 35
UPDATE vocabulary SET image_url='vocab_generated/vocab_0b360c74.png' WHERE id=997 AND word='熱い' AND (image_url IS NULL OR image_url='');
UPDATE vocabulary SET image_url='vocab_generated/vocab_c2e66965.png' WHERE id=998 AND word='厚い' AND (image_url IS NULL OR image_url='');
UPDATE vocabulary SET image_url='vocab_generated/vocab_28b8fafc.png' WHERE id=999 AND word='薄い' AND (image_url IS NULL OR image_url='');
UPDATE vocabulary SET image_url='vocab_generated/vocab_f9094c05.png' WHERE id=1005 AND word='太い' AND (image_url IS NULL OR image_url='');
UPDATE vocabulary SET image_url='vocab_generated/vocab_e1dd2c24.png' WHERE id=1006 AND word='細い' AND (image_url IS NULL OR image_url='');
UPDATE vocabulary SET image_url='vocab_generated/vocab_2506d35d.png' WHERE id=1007 AND word='低い' AND (image_url IS NULL OR image_url='');
UPDATE vocabulary SET image_url='vocab_generated/vocab_64e81e00.png' WHERE id=995 AND word='同じ' AND (image_url IS NULL OR image_url='');
UPDATE vocabulary SET image_url='vocab_generated/vocab_91e67413.png' WHERE id=1000 AND word='うるさい' AND (image_url IS NULL OR image_url='');
UPDATE vocabulary SET image_url='vocab_generated/vocab_df3415f0.png' WHERE id=1001 AND word='汚い' AND (image_url IS NULL OR image_url='');
UPDATE vocabulary SET image_url='vocab_generated/vocab_2760b52b.png' WHERE id=1002 AND word='強い' AND (image_url IS NULL OR image_url='');
UPDATE vocabulary SET image_url='vocab_generated/vocab_af3889af.png' WHERE id=1003 AND word='弱い' AND (image_url IS NULL OR image_url='');
UPDATE vocabulary SET image_url='vocab_generated/vocab_e7002cbd.png' WHERE id=1004 AND word='速い' AND (image_url IS NULL OR image_url='');
UPDATE vocabulary SET image_url='vocab_generated/vocab_957021ef.png' WHERE id=1009 AND word='まずい' AND (image_url IS NULL OR image_url='');
UPDATE vocabulary SET image_url='vocab_generated/vocab_fdc0cb4a.png' WHERE id=1010 AND word='温い' AND (image_url IS NULL OR image_url='');
UPDATE vocabulary SET image_url='vocab_generated/vocab_23fe1cbf.png' WHERE id=1008 AND word='欲しい' AND (image_url IS NULL OR image_url='');
UPDATE vocabulary SET image_url='vocab_generated/vocab_6d489aa9.png' WHERE id=1027 AND word='乗る' AND (image_url IS NULL OR image_url='');
UPDATE vocabulary SET image_url='vocab_generated/vocab_8108c093.png' WHERE id=1011 AND word='降りる' AND (image_url IS NULL OR image_url='');
UPDATE vocabulary SET image_url='vocab_generated/vocab_519b1182.png' WHERE id=1023 AND word='着く' AND (image_url IS NULL OR image_url='');
UPDATE vocabulary SET image_url='vocab_generated/vocab_631f23bf.png' WHERE id=1025 AND word='止まる' AND (image_url IS NULL OR image_url='');
UPDATE vocabulary SET image_url='vocab_generated/vocab_aaf0ce71.png' WHERE id=1012 AND word='かかる' AND (image_url IS NULL OR image_url='');
UPDATE vocabulary SET image_url='vocab_generated/vocab_8f24d759.png' WHERE id=1022 AND word='住む' AND (image_url IS NULL OR image_url='');
UPDATE vocabulary SET image_url='vocab_generated/vocab_2ceb7f34.png' WHERE id=1024 AND word='勤める' AND (image_url IS NULL OR image_url='');
UPDATE vocabulary SET image_url='vocab_generated/vocab_569a6451.png' WHERE id=1026 AND word='無くす' AND (image_url IS NULL OR image_url='');
UPDATE vocabulary SET image_url='vocab_generated/vocab_813851fe.png' WHERE id=1021 AND word='吸う' AND (image_url IS NULL OR image_url='');
UPDATE vocabulary SET image_url='vocab_generated/vocab_9c6cf905.png' WHERE id=1019 AND word='死ぬ' AND (image_url IS NULL OR image_url='');
UPDATE vocabulary SET image_url='vocab_generated/vocab_54f5f551.png' WHERE id=1014 AND word='かける' AND (image_url IS NULL OR image_url='');
UPDATE vocabulary SET image_url='vocab_generated/vocab_03c57604.png' WHERE id=1013 AND word='掛ける' AND (image_url IS NULL OR image_url='');
UPDATE vocabulary SET image_url='vocab_generated/vocab_daf8608f.png' WHERE id=1016 AND word='切る' AND (image_url IS NULL OR image_url='');
UPDATE vocabulary SET image_url='vocab_generated/vocab_c4cf1cf7.png' WHERE id=1020 AND word='締める' AND (image_url IS NULL OR image_url='');
UPDATE vocabulary SET image_url='vocab_generated/vocab_302067fd.png' WHERE id=1028 AND word='貼る' AND (image_url IS NULL OR image_url='');
UPDATE vocabulary SET image_url='vocab_generated/vocab_9bdfed18.png' WHERE id=1030 AND word='コピーする' AND (image_url IS NULL OR image_url='');
UPDATE vocabulary SET image_url='vocab_generated/vocab_4c0a5a5a.png' WHERE id=1015 AND word='消える' AND (image_url IS NULL OR image_url='');
UPDATE vocabulary SET image_url='vocab_generated/vocab_14d5c616.png' WHERE id=1018 AND word='差す' AND (image_url IS NULL OR image_url='');
UPDATE vocabulary SET image_url='vocab_generated/vocab_0706c184.png' WHERE id=1017 AND word='曇る' AND (image_url IS NULL OR image_url='');
UPDATE vocabulary SET image_url='vocab_generated/vocab_20cff071.png' WHERE id=1029 AND word='吹く' AND (image_url IS NULL OR image_url='');
COMMIT;
