"""SRS-Modelle: CardReviewState, ReviewLog, UserSRSSettings

Revision ID: 4546727db353
Revises: 98255162a434
Create Date: 2026-04-12 16:37:22.139258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4546727db353'
down_revision = '98255162a434'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_srs_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('desired_retention', sa.Float(), nullable=True),
    sa.Column('daily_new_cards', sa.Integer(), nullable=True),
    sa.Column('daily_review_limit', sa.Integer(), nullable=True),
    sa.Column('fsrs_parameters', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('card_review_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('fsrs_card_state', sa.Text(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('lapses', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['lesson_content.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'content_id', name='uq_user_content_review')
    )
    with op.batch_alter_table('card_review_state', schema=None) as batch_op:
        batch_op.create_index('ix_card_review_due', ['user_id', 'due_date', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_card_review_state_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_card_review_state_user_id'), ['user_id'], unique=False)

    op.create_table('review_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=False),
    sa.Column('time_taken_ms', sa.Integer(), nullable=True),
    sa.Column('fsrs_review_log', sa.Text(), nullable=True),
    sa.Column('scheduled_days', sa.Integer(), nullable=True),
    sa.Column('elapsed_days', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['lesson_content.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_log_reviewed_at'), ['reviewed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_log_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('course_purchase', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_purchase_postfinance_transaction_id'))
        batch_op.drop_column('postfinance_transaction_id')

    with op.batch_alter_table('lesson_purchase', schema=None) as batch_op:
        batch_op.alter_column('provider_transaction_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.BigInteger(),
               existing_nullable=True,
               postgresql_using='provider_transaction_id::bigint')
        batch_op.drop_index(batch_op.f('ix_lesson_purchase_postfinance_transaction_id'))
        batch_op.create_index(batch_op.f('ix_lesson_purchase_provider_transaction_id'), ['provider_transaction_id'], unique=False)
        batch_op.drop_column('postfinance_transaction_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_purchase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('postfinance_transaction_id', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_lesson_purchase_provider_transaction_id'))
        batch_op.create_index(batch_op.f('ix_lesson_purchase_postfinance_transaction_id'), ['postfinance_transaction_id'], unique=False)
        batch_op.alter_column('provider_transaction_id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('course_purchase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('postfinance_transaction_id', sa.BIGINT(), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_course_purchase_postfinance_transaction_id'), ['postfinance_transaction_id'], unique=False)

    with op.batch_alter_table('review_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_review_log_reviewed_at'))

    op.drop_table('review_log')
    with op.batch_alter_table('card_review_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_card_review_state_user_id'))
        batch_op.drop_index(batch_op.f('ix_card_review_state_due_date'))
        batch_op.drop_index('ix_card_review_due')

    op.drop_table('card_review_state')
    op.drop_table('user_srs_settings')
    # ### end Alembic commands ###
