"""Grammar: romaji Feld hinzugefuegt

Revision ID: 48d1c6108e0c
Revises: 4546727db353
Create Date: 2026-04-12 17:45:21.641274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48d1c6108e0c'
down_revision = '4546727db353'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grammar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('romaji', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grammar', schema=None) as batch_op:
        batch_op.drop_column('romaji')

    # ### end Alembic commands ###
