"""Grammar: structure von VARCHAR(255) auf Text erweitert

Revision ID: 5fdd334f9400
Revises: 48d1c6108e0c
Create Date: 2026-04-12 18:04:03.667396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fdd334f9400'
down_revision = '48d1c6108e0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grammar', schema=None) as batch_op:
        batch_op.alter_column('structure',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grammar', schema=None) as batch_op:
        batch_op.alter_column('structure',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
