"""Phase 6: Gamification, Achievements, DailyAggregate

Revision ID: 6730297e0374
Revises: c866cbc1bf97
Create Date: 2026-04-14 20:19:02.731035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6730297e0374'
down_revision = 'c866cbc1bf97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_review_aggregate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=False),
    sa.Column('total_reviews', sa.Integer(), nullable=False),
    sa.Column('correct_reviews', sa.Integer(), nullable=False),
    sa.Column('again_count', sa.Integer(), nullable=False),
    sa.Column('hard_count', sa.Integer(), nullable=False),
    sa.Column('good_count', sa.Integer(), nullable=False),
    sa.Column('easy_count', sa.Integer(), nullable=False),
    sa.Column('total_time_ms', sa.BigInteger(), nullable=False),
    sa.Column('xp_earned', sa.Integer(), nullable=False),
    sa.Column('new_cards_learned', sa.Integer(), nullable=False),
    sa.Column('cards_leveled_up', sa.Integer(), nullable=False),
    sa.Column('cards_leveled_down', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'review_date', name='uq_user_daily_agg')
    )
    with op.batch_alter_table('daily_review_aggregate', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_review_aggregate_review_date'), ['review_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_review_aggregate_user_id'), ['user_id'], unique=False)

    op.create_table('user_achievement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievement_key', sa.String(length=50), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(), nullable=True),
    sa.Column('notified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'achievement_key', name='uq_user_achievement')
    )
    with op.batch_alter_table('user_achievement', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_achievement_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.Integer(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('total_reviews', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('total_mastered', sa.Integer(), server_default='0', nullable=False))

    with op.batch_alter_table('user_srs_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('streak_freezes_available', sa.Integer(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('last_freeze_replenish', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('leech_threshold', sa.Integer(), server_default='8', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_srs_settings', schema=None) as batch_op:
        batch_op.drop_column('leech_threshold')
        batch_op.drop_column('last_freeze_replenish')
        batch_op.drop_column('streak_freezes_available')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('total_mastered')
        batch_op.drop_column('total_reviews')
        batch_op.drop_column('level')

    with op.batch_alter_table('user_achievement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_achievement_user_id'))

    op.drop_table('user_achievement')
    with op.batch_alter_table('daily_review_aggregate', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_review_aggregate_user_id'))
        batch_op.drop_index(batch_op.f('ix_daily_review_aggregate_review_date'))

    op.drop_table('daily_review_aggregate')
    # ### end Alembic commands ###
