"""Add AI tracking fields to LessonContent

Revision ID: 6a0198a5b907
Revises: 
Create Date: 2025-07-08 20:06:59.324452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a0198a5b907'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('generated_by_ai', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('ai_generation_details', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_content', schema=None) as batch_op:
        batch_op.drop_column('ai_generation_details')
        batch_op.drop_column('generated_by_ai')

    op.create_table('user_card_progress',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('learnable_id', sa.INTEGER(), nullable=False),
    sa.Column('learnable_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('current_interval', sa.INTEGER(), nullable=False),
    sa.Column('ease_factor', sa.FLOAT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('due_at', sa.DATETIME(), nullable=False),
    sa.Column('repetitions', sa.INTEGER(), nullable=False),
    sa.Column('lapses', sa.INTEGER(), nullable=False),
    sa.Column('last_reviewed_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'learnable_id', 'learnable_type', name=op.f('uq_user_learnable'))
    )
    with op.batch_alter_table('user_card_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_card_progress_user_due'), ['user_id', 'due_at'], unique=False)

    # ### end Alembic commands ###
