"""Add status and created_by_ai to content models

Revision ID: 78336f26cb3e
Revises: 6a0198a5b907
Create Date: 2025-07-11 14:19:27.999897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78336f26cb3e'
down_revision = '6a0198a5b907'
branch_labels = None
depends_on = None


def table_has_column(table, column):
    conn = op.get_bind()
    insp = sa.inspect(conn)
    columns = insp.get_columns(table)
    return any(c['name'] == column for c in columns)

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if not table_has_column('grammar', 'status'):
        with op.batch_alter_table('grammar', schema=None) as batch_op:
            batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default='approved'))

    if not table_has_column('grammar', 'created_by_ai'):
        with op.batch_alter_table('grammar', schema=None) as batch_op:
            batch_op.add_column(sa.Column('created_by_ai', sa.Boolean(), nullable=False, server_default=sa.false()))

    if not table_has_column('kanji', 'status'):
        with op.batch_alter_table('kanji', schema=None) as batch_op:
            batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default='approved'))

    if not table_has_column('kanji', 'created_by_ai'):
        with op.batch_alter_table('kanji', schema=None) as batch_op:
            batch_op.add_column(sa.Column('created_by_ai', sa.Boolean(), nullable=False, server_default=sa.false()))

    if not table_has_column('vocabulary', 'status'):
        with op.batch_alter_table('vocabulary', schema=None) as batch_op:
            batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default='approved'))

    if not table_has_column('vocabulary', 'created_by_ai'):
        with op.batch_alter_table('vocabulary', schema=None) as batch_op:
            batch_op.add_column(sa.Column('created_by_ai', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vocabulary', schema=None) as batch_op:
        batch_op.drop_column('created_by_ai')
        batch_op.drop_column('status')

    with op.batch_alter_table('kanji', schema=None) as batch_op:
        batch_op.drop_column('created_by_ai')
        batch_op.drop_column('status')

    with op.batch_alter_table('grammar', schema=None) as batch_op:
        batch_op.drop_column('created_by_ai')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
