"""Add advanced quiz features

Revision ID: 8601eb489f39
Revises: 78336f26cb3e
Create Date: 2025-07-11 20:43:16.519896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8601eb489f39'
down_revision = '78336f26cb3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson_content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_type', sa.String(length=50), nullable=True))

    with op.batch_alter_table('quiz_question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hint', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('difficulty_level', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_question', schema=None) as batch_op:
        batch_op.drop_column('difficulty_level')
        batch_op.drop_column('hint')

    with op.batch_alter_table('lesson_content', schema=None) as batch_op:
        batch_op.drop_column('quiz_type')

    # ### end Alembic commands ###
