"""Vocabulary: meaning_de Feld hinzugefuegt

Revision ID: c866cbc1bf97
Revises: 5fdd334f9400
Create Date: 2026-04-12 20:12:56.533821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c866cbc1bf97'
down_revision = '5fdd334f9400'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vocabulary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meaning_de', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vocabulary', schema=None) as batch_op:
        batch_op.drop_column('meaning_de')

    # ### end Alembic commands ###
