"""Befüllt meaning_de für alle Vokabeln der deutschen Lektionen."""
import sys
import io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

from app import create_app, db
from app.models import Vocabulary

app = create_app()

# Deutsche Übersetzungen: ID -> meaning_de
translations = {
    6: "Freut mich (bei erster Begegnung)",
    9: "Entschuldigung / Verzeihung",
    10: "Ja",
    11: "Nein / Keine Ursache",
    20: "ich",
    21: "wir",
    22: "du / Sie",
    23: "diese Person, er, sie",
    24: "diese Person (höflich)",
    25: "meine Damen und Herren, alle",
    26: "Lehrer, Meister",
    27: "Lehrer (Beruf)",
    28: "Student",
    29: "Firmenangestellter",
    30: "Angestellter von ~",
    31: "Bankangestellter",
    32: "Arzt",
    33: "Forscher, Wissenschaftler",
    34: "Ingenieur",
    35: "Universität",
    36: "Krankenhaus",
    37: "Elektrizität, Licht",
    38: "wer",
    39: "wer (höflich)",
    40: "~ Jahre alt",
    41: "wie alt",
    42: "Entschuldigen Sie, aber",
    43: "Wie ist Ihr Name?",
    44: "Freut mich, Sie kennenzulernen",
    45: "USA",
    46: "Grossbritannien",
    47: "Indien",
    48: "Indonesien",
    49: "Südkorea",
    50: "Thailand",
    51: "China",
    52: "Deutschland",
    53: "Japan",
    54: "Frankreich",
    55: "Brasilien",
    56: "dies (hier)",
    57: "das (bei dir)",
    58: "das (dort drüben)",
    59: "diese/r/s ~ (Bestimmungswort)",
    60: "diese/r/s ~ (bei dir, Bestimmungswort)",
    61: "jene/r/s ~ (dort drüben, Bestimmungswort)",
    62: "Buch",
    63: "Wörterbuch",
    64: "Zeitschrift",
    65: "Zeitung",
    66: "Heft, Notizbuch",
    67: "Taschenkalender, Notizbuch",
    68: "Visitenkarte",
    69: "Karte",
    70: "Bleistift",
    71: "Kugelschreiber",
    72: "Druckbleistift",
    73: "Schlüssel",
    74: "Uhr",
    75: "Regenschirm",
    76: "Tasche, Aktentasche",
    77: "Fernseher",
    78: "Radio",
    79: "Kamera",
    80: "Computer",
    81: "Auto, Fahrzeug",
    82: "Schreibtisch",
    83: "Schokolade",
    84: "Kaffee",
    85: "Englisch (Sprache)",
    86: "Japanisch (Sprache)",
    87: "was",
    88: "so, genau, stimmt",
    89: "Nein, das stimmt nicht / Es ist anders",
    90: "Ach so? / Verstehe",
    91: "ähm, also (Zögern)",
    92: "Souvenir, Mitbringsel",
    93: "danke (informell)",
    94: "bitte (anbietend)",
    95: "hier, dieser Ort",
    96: "dort, dieser Ort (bei dir)",
    97: "dort drüben, jener Ort",
    98: "wo, welcher Ort",
    99: "hier entlang, hier (höflich)",
    100: "dort entlang, dort (höflich)",
    101: "dort drüben entlang (höflich)",
    102: "welche Richtung, wo (höflich)",
    103: "Klassenzimmer",
    104: "Speisesaal, Kantine",
    105: "Büro",
    106: "Konferenzraum",
    107: "Rezeption, Empfang",
    108: "Lobby",
    109: "Zimmer",
    110: "Toilette",
    111: "Treppe",
    112: "Aufzug, Lift",
    113: "Rolltreppe",
    114: "Toilette (höflich)",
    115: "Getränkeautomat",
    116: "Abteilung, Verkaufstheke",
    117: "Untergeschoss, Keller",
    118: "Erdgeschoss (1. Stock)",
    119: "zweiter Stock",
    120: "dritter Stock",
    121: "welcher Stock / welches Stockwerk",
    122: "Yen (japanische Währung)",
    123: "wie viel (kostet es)",
    124: "hundert",
    125: "tausend",
    126: "zehntausend",
    127: "Schuhe",
    128: "Krawatte",
    129: "Wein",
    130: "Land, Heimat",
    131: "Firma, Unternehmen",
    132: "Zuhause, Haus",
    133: "Telefon",
    134: "Telefonnummer",
    135: "welche Nummer",
    136: "aufstehen, aufwachen",
    137: "schlafen, ins Bett gehen",
    138: "arbeiten",
    139: "sich ausruhen, frei nehmen",
    140: "lernen, studieren",
    141: "enden, aufhören",
    142: "anfangen, beginnen",
    143: "jetzt",
    144: "Uhr (Zähler)",
    145: "Minute (Zähler)",
    146: "halb (Uhrzeit)",
    147: "vormittags, Morgen",
    148: "nachmittags, Nachmittag",
    149: "Morgen",
    150: "Mittag, tagsüber",
    151: "Abend, Nacht",
    152: "Nacht",
    153: "vorgestern",
    154: "gestern",
    155: "heute",
    156: "morgen",
    157: "übermorgen",
    158: "heute Morgen",
    159: "heute Abend",
    160: "Ruhe, Feiertag, freier Tag",
    161: "Mittagspause",
    162: "jeden Tag",
    163: "jeden Morgen",
    164: "jeden Abend",
    165: "Sonntag",
    166: "Montag",
    167: "Dienstag",
    168: "Mittwoch",
    169: "Donnerstag",
    170: "Freitag",
    171: "Samstag",
    172: "wie viel Uhr, um welche Zeit",
    173: "welche Minute",
    174: "welcher Wochentag",
    175: "Bank",
    176: "Post, Postamt",
    177: "Bibliothek",
    178: "Kunstmuseum",
    179: "Das ist hart / Das ist schwierig",
    180: "Mal sehen / Genau, stimmt",
    181: "gehen",
    182: "kommen",
    183: "nach Hause gehen, zurückkehren",
    184: "Schule",
    185: "Supermarkt",
    186: "Bahnhof",
    187: "Flugzeug",
    188: "Schiff, Boot",
    189: "Zug (elektrisch)",
    190: "Bus",
    191: "Taxi",
    192: "Fahrrad",
    193: "zu Fuss",
    194: "Person, Mensch",
    195: "Freund",
    196: "Familie",
    197: "allein",
    198: "letzte Woche",
    199: "diese Woche",
    200: "nächste Woche",
    201: "letzten Monat",
    202: "diesen Monat",
    203: "nächsten Monat",
    204: "letztes Jahr",
    205: "dieses Jahr",
    206: "nächstes Jahr",
    207: "wann",
    208: "Geburtstag",
    209: "Nahverkehrszug, Bummelzug",
    210: "Schnellzug",
    211: "Shinkansen (Hochgeschwindigkeitszug)",
    212: "U-Bahn",
    213: "Kaufhaus",
    214: "Zoo",
    215: "Park",
    216: "Geschäft, Laden",
    217: "Restaurant",
    218: "Kirschblütenschau (Hanami)",
    219: "zusammen, gemeinsam",
    220: "ja (informell)",
    221: "Das klingt gut",
}

with app.app_context():
    updated = 0
    not_found = 0
    for vid, meaning_de in translations.items():
        v = db.session.get(Vocabulary, vid)
        if v:
            v.meaning_de = meaning_de
            updated += 1
        else:
            print(f"  WARNUNG: ID {vid} nicht gefunden")
            not_found += 1
    db.session.commit()
    print(f"{updated} Vokabeln mit meaning_de aktualisiert ({not_found} nicht gefunden)")
